Shortening pipeline

diff --git a/03-AML_AzDO_MLOpsDevelopment/.pipelines/autoencoder-real-time-endpoint-cd.yml b/03-AML_AzDO_MLOpsDevelopment/.pipelines/autoencoder-real-time-endpoint-cd.yml
--- a/03-AML_AzDO_MLOpsDevelopment/.pipelines/autoencoder-real-time-endpoint-cd.yml
+++ b/03-AML_AzDO_MLOpsDevelopment/.pipelines/autoencoder-real-time-endpoint-cd.yml
@@ -45,48 +45,48 @@ stages:
         projectId: '$(resources.pipeline.model-train-ci.projectID)'
         pipelineId: '$(resources.pipeline.model-train-ci.pipelineID)'
         artifactBuildId: ${{ parameters.artifactBuildId }}
-    - task: AzureCLI@1
-      displayName: 'Install AzureML CLI'
-      inputs:
-        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-        scriptLocation: inlineScript
-        workingDirectory: $(Build.SourcesDirectory)
-        inlineScript: 'az extension add --source https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.27.0-py3-none-any.whl --yes'
-    - task: AzureCLI@1
-      displayName: "Deploy to ACI (CLI)"
-      inputs:
-        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-        scriptLocation: inlineScript
-        workingDirectory: $(Build.SourcesDirectory)/$(SOURCES_DIR_TRAIN)/scoring
-        inlineScript: |
-          set -e # fail on error
+  #   - task: AzureCLI@1
+  #     displayName: 'Install AzureML CLI'
+  #     inputs:
+  #       azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+  #       scriptLocation: inlineScript
+  #       workingDirectory: $(Build.SourcesDirectory)
+  #       inlineScript: 'az extension add --source https://azurecliext.blob.core.windows.net/release/azure_cli_ml-1.27.0-py3-none-any.whl --yes'
+  #   - task: AzureCLI@1
+  #     displayName: "Deploy to ACI (CLI)"
+  #     inputs:
+  #       azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+  #       scriptLocation: inlineScript
+  #       workingDirectory: $(Build.SourcesDirectory)/$(SOURCES_DIR_TRAIN)/scoring
+  #       inlineScript: |
+  #         set -e # fail on error
           
-          # az ml model deploy --name $(ACI_DEPLOYMENT_NAME) --model '$(get_model.MODEL_NAME):$(get_model.MODEL_VERSION)' \
-          # --ic inference_config.yml \
-          # --dc deployment_config_aci.yml \
-          # -g $(RESOURCE_GROUP) --workspace-name $(WORKSPACE_NAME) \
-          # --overwrite -v --ae True
-          echo "##vso[task.setvariable variable=MODEL_NAME;isOutput=true]$(get_model.MODEL_NAME)"
-          echo "##vso[task.setvariable variable=MODEL_NAME;isOutput=true]$(get_model.MODEL_VERSION)"
-        name: 'deploy_to_aci'
-    - task: AzureCLI@1
-      displayName: 'Smoke test'
-      inputs:
-        azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
-        scriptLocation: inlineScript
-        workingDirectory: $(Build.SourcesDirectory)/$(SOURCES_DIR_TRAIN)/scoring
-        inlineScript: |
-          set -e # fail on error
-          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
-          python -m smoke_test_scoring_service --type ACI --service "$(ACI_DEPLOYMENT_NAME)"
+  #         # az ml model deploy --name $(ACI_DEPLOYMENT_NAME) --model '$(get_model.MODEL_NAME):$(get_model.MODEL_VERSION)' \
+  #         # --ic inference_config.yml \
+  #         # --dc deployment_config_aci.yml \
+  #         # -g $(RESOURCE_GROUP) --workspace-name $(WORKSPACE_NAME) \
+  #         # --overwrite -v --ae True
+  #         echo "##vso[task.setvariable variable=MODEL_NAME;isOutput=true]$(get_model.MODEL_NAME)"
+  #         echo "##vso[task.setvariable variable=MODEL_NAME;isOutput=true]$(get_model.MODEL_VERSION)"
+  #       name: 'deploy_to_aci'
+  #   - task: AzureCLI@1
+  #     displayName: 'Smoke test'
+  #     inputs:
+  #       azureSubscription: '$(WORKSPACE_SVC_CONNECTION)'
+  #       scriptLocation: inlineScript
+  #       workingDirectory: $(Build.SourcesDirectory)/$(SOURCES_DIR_TRAIN)/scoring
+  #       inlineScript: |
+  #         set -e # fail on error
+  #         export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
+  #         python -m smoke_test_scoring_service --type ACI --service "$(ACI_DEPLOYMENT_NAME)"
 
-  - job: "Package_Model"
-    container: mlops
-    displayName: "Package_Model"
-    variables:
-          MODEL_NAME: $[ dependencies.Deploy_ACI.outputs['deploy_to_aci.MODEL_NAME'] ]
-          MODEL_VERSION: $[ dependencies.Deploy_ACI.outputs['deploy_to_aci.MODEL_VERSION'] ]
-    steps:
+  # - job: "Package_Model"
+  #   container: mlops
+  #   displayName: "Package_Model"
+  #   variables:
+  #         MODEL_NAME: $[ dependencies.Deploy_ACI.outputs['deploy_to_aci.MODEL_NAME'] ]
+  #         MODEL_VERSION: $[ dependencies.Deploy_ACI.outputs['deploy_to_aci.MODEL_VERSION'] ]
+  #   steps:
     - task: AzureCLI@1
       displayName: 'Download Model Package (Artifacts and Dockerfile)'
       inputs:
